"""User and satisfaction survey relation

Revision ID: 3043deb86ab1
Revises: 6f21a2c16d81
Create Date: 2025-09-25 18:29:54.198498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3043deb86ab1'
down_revision: Union[str, Sequence[str], None] = '6f21a2c16d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satisfaction_surveys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satisfaction_surveys_id'), 'satisfaction_surveys', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_satisfaction_surveys_id'), table_name='satisfaction_surveys')
    op.drop_table('satisfaction_surveys')
    # ### end Alembic commands ###
