"""add unique parameter to cedula

Revision ID: 441949664305
Revises: 1811efe3130d
Create Date: 2025-10-01 11:05:18.647798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441949664305'
down_revision: Union[str, Sequence[str], None] = '1811efe3130d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cedula'), table_name='users')
    op.create_index(op.f('ix_users_cedula'), 'users', ['cedula'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cedula'), table_name='users')
    op.create_index(op.f('ix_users_cedula'), 'users', ['cedula'], unique=False)
    # ### end Alembic commands ###
