"""update UUID types and add cascade deletes

Revision ID: 848f979e74a5
Revises: c44eb917d1ee
Create Date: 2025-10-15 21:02:39.245801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848f979e74a5'
down_revision: Union[str, Sequence[str], None] = 'c44eb917d1ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assignments_id_area_fkey'), 'assignments', type_='foreignkey')
    op.drop_constraint(op.f('assignments_id_status_fkey'), 'assignments', type_='foreignkey')
    op.drop_constraint(op.f('assignments_training_id_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'statuses', ['id_status'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assignments', 'areas', ['id_area'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assignments', 'trainings', ['training_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('options_question_id_fkey'), 'options', type_='foreignkey')
    op.create_foreign_key(None, 'options', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('questionnaires_training_id_fkey'), 'questionnaires', type_='foreignkey')
    op.create_foreign_key(None, 'questionnaires', 'trainings', ['training_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('questions_question_type_id_fkey'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('questions_questionnaire_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'questionnaires', ['questionnaire_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'questions', 'question_types', ['question_type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('results_user_id_fkey'), 'results', type_='foreignkey')
    op.drop_constraint(op.f('results_questionnaire_id_fkey'), 'results', type_='foreignkey')
    op.create_foreign_key(None, 'results', 'questionnaires', ['questionnaire_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'results', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('satisfaction_surveys_user_id_fkey'), 'satisfaction_surveys', type_='foreignkey')
    op.create_foreign_key(None, 'satisfaction_surveys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('trainings_user_id_fkey'), 'trainings', type_='foreignkey')
    op.create_foreign_key(None, 'trainings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_answers_question_id_fkey'), 'user_answers', type_='foreignkey')
    op.drop_constraint(op.f('user_answers_user_id_fkey'), 'user_answers', type_='foreignkey')
    op.drop_constraint(op.f('user_answers_option_id_fkey'), 'user_answers', type_='foreignkey')
    op.create_foreign_key(None, 'user_answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_answers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_answers', 'options', ['option_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_area_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'areas', ['area_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('users_area_id_fkey'), 'users', 'areas', ['area_id'], ['id'])
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.create_foreign_key(op.f('user_answers_option_id_fkey'), 'user_answers', 'options', ['option_id'], ['id'])
    op.create_foreign_key(op.f('user_answers_user_id_fkey'), 'user_answers', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_answers_question_id_fkey'), 'user_answers', 'questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'trainings', type_='foreignkey')
    op.create_foreign_key(op.f('trainings_user_id_fkey'), 'trainings', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'satisfaction_surveys', type_='foreignkey')
    op.create_foreign_key(op.f('satisfaction_surveys_user_id_fkey'), 'satisfaction_surveys', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.create_foreign_key(op.f('results_questionnaire_id_fkey'), 'results', 'questionnaires', ['questionnaire_id'], ['id'])
    op.create_foreign_key(op.f('results_user_id_fkey'), 'results', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_questionnaire_id_fkey'), 'questions', 'questionnaires', ['questionnaire_id'], ['id'])
    op.create_foreign_key(op.f('questions_question_type_id_fkey'), 'questions', 'question_types', ['question_type_id'], ['id'])
    op.drop_constraint(None, 'questionnaires', type_='foreignkey')
    op.create_foreign_key(op.f('questionnaires_training_id_fkey'), 'questionnaires', 'trainings', ['training_id'], ['id'])
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.create_foreign_key(op.f('options_question_id_fkey'), 'options', 'questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_training_id_fkey'), 'assignments', 'trainings', ['training_id'], ['id'])
    op.create_foreign_key(op.f('assignments_id_status_fkey'), 'assignments', 'statuses', ['id_status'], ['id'])
    op.create_foreign_key(op.f('assignments_id_area_fkey'), 'assignments', 'areas', ['id_area'], ['id'])
    # ### end Alembic commands ###
