"""add areas for users

Revision ID: dbf4fedc0bd9
Revises: be36569b06fb
Create Date: 2025-09-30 10:46:49.660031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf4fedc0bd9'
down_revision: Union[str, Sequence[str], None] = 'be36569b06fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=True)
    op.create_index(op.f('ix_areas_name'), 'areas', ['name'], unique=False)
    op.add_column('assignments', sa.Column('id_area', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('assignments_id_user_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'areas', ['id_area'], ['id'])
    op.drop_column('assignments', 'id_user')
    op.add_column('users', sa.Column('area_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'area_id')
    op.add_column('assignments', sa.Column('id_user', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_id_user_fkey'), 'assignments', 'users', ['id_user'], ['id'])
    op.drop_column('assignments', 'id_area')
    op.drop_index(op.f('ix_areas_name'), table_name='areas')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
