"""create user training table

Revision ID: dfce32d47971
Revises: ce0da1b8a52b
Create Date: 2025-10-17 22:30:24.594644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfce32d47971'
down_revision: Union[str, Sequence[str], None] = 'ce0da1b8a52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_trainings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('progress', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id_assignments', sa.Uuid(), nullable=False),
    sa.Column('id_training', sa.Uuid(), nullable=False),
    sa.Column('id_status', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id_assignments'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_status'], ['statuses.id'], ),
    sa.ForeignKeyConstraint(['id_training'], ['trainings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_trainings_id'), 'user_trainings', ['id'], unique=True)
    op.drop_constraint(op.f('assignments_id_status_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'statuses', ['id_status'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_id_status_fkey'), 'assignments', 'statuses', ['id_status'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_trainings_id'), table_name='user_trainings')
    op.drop_table('user_trainings')
    # ### end Alembic commands ###
