"""user, trainings, assigment relation

Revision ID: e9983da90df5
Revises: 3b287ab38555
Create Date: 2025-09-26 10:46:51.262949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9983da90df5'
down_revision: Union[str, Sequence[str], None] = '3b287ab38555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('url_video', sa.String(), nullable=False),
    sa.Column('url_image', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainings_id'), 'trainings', ['id'], unique=True)
    op.create_index(op.f('ix_trainings_title'), 'trainings', ['title'], unique=False)
    op.add_column('assignments', sa.Column('training_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'assignments', 'trainings', ['training_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'training_id')
    op.drop_index(op.f('ix_trainings_title'), table_name='trainings')
    op.drop_index(op.f('ix_trainings_id'), table_name='trainings')
    op.drop_table('trainings')
    # ### end Alembic commands ###
