from uuid import UUID
from application.ports.base_repository import IBaseRepository
from domain.models.users.refresh_token import RefreshToken
from domain.models.users.user import User
from typing import Optional

class IUserRepository(IBaseRepository[User]):
    def get_by_email(self, email: str) -> Optional[User]: ...
    
    def create_refresh_token(self, token: RefreshToken) -> RefreshToken: ...
    
    def delete_refresh_token(self, user_id: str) -> None: ...
    
    def get_refresh_token(self, token_hash: str) -> RefreshToken: ...
    
    def get_by_cedula(self, cedula: str) -> Optional[User]: ...
    
    def get_by_area(self, id_area: UUID) -> list[User]: ...
