from typing import Protocol

from fastapi import Request

class MediaStoragePort(Protocol):
    def save(self, file_bytes: bytes, filename: str, folder: str) -> str: ...
    
    def get(self, filepath: str) -> bytes: ...
    
    def delete(self, filepath: str) -> None: ...
    
    def build_url(self, filepath: str, request: Request) -> str: ...
