from uuid import UUID
from application.ports.base_repository import IBaseRepository
from domain.models.evaluations.user_answer import UserAnswer

class IUserAnswerRepository(IBaseRepository[UserAnswer]):
    def get_by_user_and_training(self, training_id: UUID, user_id: UUID) -> list[UserAnswer]: ...
    
    def get_by_user_and_questionnaire(self, user_id, questionnaire_id): ...
    
    def get_existing(self, question_id: UUID, option_id: UUID): ...
    
    def get_by_user_and_questionnaire(self, user_id: UUID, questionnaire_id: UUID): ...
    
    def get_existing_with_option(self, user_id: UUID, question_id: UUID, option_id: UUID): ...
    
    def get_all_by_user_and_question(self, user_id: UUID, question_id: UUID): ...
    
    def delete_by_user_and_question(self, user_id: UUID, question_id: UUID): ...
    
    def get_all_by_user_and_question(self, user_id: UUID, question_id: UUID): ...
    
    def create_many(self, entities: list[UserAnswer]) -> list[UserAnswer]: ...